### ISSUE TITLE
ServiceAddress from consul catalog can be empty

### ISSUE THREAD

**Issue by gdchamal** [mardiros/blacksmith#43]
When ServiceAddress == "" from consul catalog response then Address (node address) must be used instead. On a local consul environment this situation occurs.

https://developer.hashicorp.com/consul/api-docs/catalog#serviceaddress

I start tried to figure how to do a PR for that, but for the moment I don't know how to provide many aliases for pydantic.Field resolution without waiting for pydantic v2 : https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#more-powerful-aliases

Example of a consul.catalog response on my local environment

```
In [13]: consul.catalog.service('api-something-v1')
Out[13]: 
[{'ID': '83818547-3128-a704-fed7-2cb482a50219',
  'Node': 'tao',
  'Address': '192.168.42.7',
  'Datacenter': 'dc1',
  'TaggedAddresses': {'lan': '192.168.42.7',
   'lan_ipv4': '192.168.42.7',
   'wan': '192.168.42.7',
   'wan_ipv4': '192.168.42.7'},
  'NodeMeta': {'consul-network-segment': ''},
  'ServiceKind': '',
  'ServiceID': '_nomad-task-9d031d52-4026-6463-2197-42c86443e30e-group-api-something-v1-api-something-v1-6543',
  'ServiceName': 'api-something-v1',
  'ServiceAddress': '',
  'ServiceWeights': {'Passing': 1, 'Warning': 1},
  'ServiceMeta': {'external-source': 'nomad'},
  'ServicePort': 6543,
  'ServiceSocketPath': '',
  'ServiceEnableTagOverride': False,
  'ServiceProxy': {'Mode': '', 'MeshGateway': {}, 'Expose': {}},
  'ServiceConnect': {},
  'CreateIndex': 183654,
  'ModifyIndex': 183654}]
```

**Comment by mardiros** [comment]
You don't think pydantic alias will be appropriate actually.

https://developer.hashicorp.com/consul/api-docs/catalog#serviceaddress
I did not aware about that.

I will fix it.

**Comment by gdchamal** [comment]
I fixed on my side (ServiceAddress is filled) using a different configuration when deploying nomad jobs registering in consul
